"""
演示模式使用的模擬資料
提供 BGG API 的模擬資料，用於演示和測試
"""

# 演示用遊戲清單
DEMO_GAMES = [
    {
        "id": 13,
        "name": "Catan",
        "year_published": 1995,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/pic2419375.jpg",
        "image": "https://cf.geekdo-images.com/original/img/A-0yDJkve0avEicYQ4HoNO-HkK8=/0x0/pic2419375.jpg",
        "rating_average": 7.2,
        "rank": 300,
        "min_players": 3,
        "max_players": 4,
        "playing_time": 90,
        "categories": ["Negotiation", "Economic"],
        "mechanics": ["Dice Rolling", "Trading"],
    },
    {
        "id": 174430,
        "name": "Gloomhaven",
        "year_published": 2017,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/e7GyV4PaNtwmalU-EQAGecwoBSI=/fit-in/200x150/pic2437871.jpg",
        "image": "https://cf.geekdo-images.com/original/img/lDN358RgcYvQfYYN6Oy2TXpifyM=/0x0/pic2437871.jpg",
        "rating_average": 8.7,
        "rank": 1,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "categories": ["Adventure", "Fantasy"],
        "mechanics": ["Card Driven", "Hand Management"],
    },
    {
        "id": 167791,
        "name": "Terraforming Mars",
        "year_published": 2016,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/wH5tKAX_qM3yN5n1m0wu4a18v0s=/fit-in/200x150/pic3536616.jpg",
        "image": "https://cf.geekdo-images.com/original/img/o8z_levBVArPUKI7ZrIysZEs9s=/0x0/pic3536616.jpg",
        "rating_average": 8.4,
        "rank": 4,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 120,
        "categories": ["Economic", "Science Fiction"],
        "mechanics": ["Card Drafting", "Hand Management"],
    },
    {
        "id": 169786,
        "name": "Scythe",
        "year_published": 2016,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/ZpuWhZuKrFry__SY8CTRuHz2r3z=/fit-in/200x150/pic3163924.jpg",
        "image": "https://cf.geekdo-images.com/original/img/enxCZt0Cn78-rlvmPvGtOej1Lfo=/0x0/pic3163924.jpg",
        "rating_average": 8.3,
        "rank": 10,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 115,
        "categories": ["Economic", "Fighting"],
        "mechanics": ["Area Control", "Variable Player Powers"],
    },
    {
        "id": 224517,
        "name": "Brass: Birmingham",
        "year_published": 2018,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/Z3yCE6XuoxQE7nI7t1X4bMKFCsQ=/fit-in/200x150/pic3490053.jpg",
        "image": "https://cf.geekdo-images.com/original/img/tQVLRtjR7IIGbSQ5_7C_WyJJyP0=/0x0/pic3490053.jpg",
        "rating_average": 8.6,
        "rank": 2,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 120,
        "categories": ["Economic", "Industry"],
        "mechanics": ["Hand Management", "Network Building"],
    },
    {
        "id": 161936,
        "name": "Pandemic Legacy: Season 1",
        "year_published": 2015,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/QNNebRZbCkFl5jYMjk7i9U6yiHc=/fit-in/200x150/pic2452831.png",
        "image": "https://cf.geekdo-images.com/original/img/P_SwsOtPLqgk5B0R6sCNkOXYIhs=/0x0/pic2452831.png",
        "rating_average": 8.6,
        "rank": 3,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 60,
        "categories": ["Medical"],
        "mechanics": ["Cooperative Play", "Hand Management"],
    },
    {
        "id": 233078,
        "name": "Wingspan",
        "year_published": 2019,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/wWlJkJo31xVPLmEPOkqiRkd5AiU=/fit-in/200x150/pic4458123.jpg",
        "image": "https://cf.geekdo-images.com/original/img/B4CGTI4_n1-pqy9q0l0kv_1SLnk=/0x0/pic4458123.jpg",
        "rating_average": 8.1,
        "rank": 25,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 70,
        "categories": ["Animals", "Card Game"],
        "mechanics": ["Card Drafting", "Engine Building"],
    },
    {
        "id": 266192,
        "name": "Wingspan: European Expansion",
        "year_published": 2019,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/5x5TuxFqEXhYdJc9RM5fU0LB4fs=/fit-in/200x150/pic4950720.jpg",
        "image": "https://cf.geekdo-images.com/original/img/qhF_N_lGFl9hLVXPD8WQEb0rZ9o=/0x0/pic4950720.jpg",
        "rating_average": 8.2,
        "rank": 100,
        "min_players": 1,
        "max_players": 5,
        "playing_time": 70,
        "categories": ["Animals", "Card Game", "Expansion"],
        "mechanics": ["Card Drafting", "Engine Building"],
    },
    {
        "id": 220308,
        "name": "Gaia Project",
        "year_published": 2017,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/wWK-kIyZCTdlfQgTQXQ3uuH_3bU=/fit-in/200x150/pic3763556.jpg",
        "image": "https://cf.geekdo-images.com/original/img/FRvPR8OC5a_l0Mm_EaxpDhguT94=/0x0/pic3763556.jpg",
        "rating_average": 8.5,
        "rank": 8,
        "min_players": 1,
        "max_players": 4,
        "playing_time": 150,
        "categories": ["Economic", "Science Fiction"],
        "mechanics": ["Area Control", "Variable Player Powers"],
    },
    {
        "id": 182028,
        "name": "Through the Ages: A New Story of Civilization",
        "year_published": 2015,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/4By6Bk_6VHTq1aWIx9R-v5Cw-Cw=/fit-in/200x150/pic2663291.jpg",
        "image": "https://cf.geekdo-images.com/original/img/jJHlPE0YiKNvvWbVxZdrT2xhU04=/0x0/pic2663291.jpg",
        "rating_average": 8.4,
        "rank": 5,
        "min_players": 2,
        "max_players": 4,
        "playing_time": 240,
        "categories": ["Civilization", "Card Game"],
        "mechanics": ["Card Drafting", "Hand Management"],
    },
]

# 演示用遊戲詳情
DEMO_GAME_DETAILS = {
    13: {
        "id": 13,
        "name": "Catan",
        "description": "In Catan, players try to be the dominant force on the island of Catan by building settlements, cities, and roads.",
        "year_published": 1995,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/pic2419375.jpg",
        "image": "https://cf.geekdo-images.com/original/img/A-0yDJkve0avEicYQ4HoNO-HkK8=/0x0/pic2419375.jpg",
        "min_players": 3,
        "max_players": 4,
        "playing_time": 90,
        "min_age": 10,
        "rating_average": 7.2,
        "rating_bayes_average": 7.0,
        "rating_users": 80000,
        "rank": 300,
        "weight_average": 2.3,
        "owned": 100000,
        "trading": 5000,
        "wanting": 2000,
        "wishing": 10000,
        "categories": ["Negotiation", "Economic"],
        "mechanics": ["Dice Rolling", "Trading", "Route Building"],
        "families": ["Catan"],
        "designers": ["Klaus Teuber"],
        "artists": ["Volkan Baga", "Tanja Donner"],
        "publishers": ["Catan Studio", "999 Games"],
        "expansions": [
            {"id": 926, "name": "Catan: 5-6 Player Extension"},
            {"id": 2807, "name": "Catan: Seafarers"},
            {"id": 4101, "name": "Catan: Cities & Knights"},
        ],
    },
    174430: {
        "id": 174430,
        "name": "Gloomhaven",
        "description": "Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives.",
        "year_published": 2017,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/e7GyV4PaNtwmalU-EQAGecwoBSI=/fit-in/200x150/pic2437871.jpg",
        "image": "https://cf.geekdo-images.com/original/img/lDN358RgcYvQfYYN6Oy2TXpifyM=/0x0/pic2437871.jpg",
        "min_players": 1,
        "max_players": 4,
        "playing_time": 120,
        "min_age": 14,
        "rating_average": 8.7,
        "rating_bayes_average": 8.5,
        "rating_users": 50000,
        "rank": 1,
        "weight_average": 3.9,
        "owned": 70000,
        "trading": 1000,
        "wanting": 5000,
        "wishing": 20000,
        "categories": ["Adventure", "Fantasy", "Fighting"],
        "mechanics": ["Card Driven", "Hand Management", "Modular Board"],
        "families": ["Gloomhaven"],
        "designers": ["Isaac Childres"],
        "artists": ["Alexandr Elichev", "Josh T. McDowell"],
        "publishers": ["Cephalofair Games"],
        "expansions": [
            {"id": 226868, "name": "Gloomhaven: Forgotten Circles"},
            {"id": 291457, "name": "Gloomhaven: Jaws of the Lion"},
        ],
    },
    167791: {
        "id": 167791,
        "name": "Terraforming Mars",
        "description": "In Terraforming Mars, you play a corporation and work together to terraform Mars.",
        "year_published": 2016,
        "thumbnail": "https://cf.geekdo-images.com/thumb/img/wH5tKAX_qM3yN5n1m0wu4a18v0s=/fit-in/200x150/pic3536616.jpg",
        "image": "https://cf.geekdo-images.com/original/img/o8z_levBVArPUKI7ZrIysZEs9s=/0x0/pic3536616.jpg",
        "min_players": 1,
        "max_players": 5,
        "playing_time": 120,
        "min_age": 12,
        "rating_average": 8.4,
        "rating_bayes_average": 8.2,
        "rating_users": 60000,
        "rank": 4,
        "weight_average": 3.2,
        "owned": 80000,
        "trading": 2000,
        "wanting": 4000,
        "wishing": 15000,
        "categories": ["Economic", "Science Fiction", "Territory Building"],
        "mechanics": ["Card Drafting", "Hand Management", "Tile Placement"],
        "families": ["Terraforming Mars"],
        "designers": ["Jacob Fryxelius"],
        "artists": ["Isaac Fryxelius"],
        "publishers": ["FryxGames", "Stronghold Games"],
        "expansions": [
            {"id": 218127, "name": "Terraforming Mars: Hellas & Elysium"},
            {"id": 231965, "name": "Terraforming Mars: Venus Next"},
        ],
    },
}

# 派對遊戲演示資料
DEMO_PARTY_GAMES = [
    {"id": 178900, "name": "Codenames", "rating_average": 7.8, "min_players": 2, "max_players": 8},
    {"id": 128882, "name": "The Resistance: Avalon", "rating_average": 7.6, "min_players": 5, "max_players": 10},
    {"id": 223040, "name": "Deception: Murder in Hong Kong", "rating_average": 7.5, "min_players": 4, "max_players": 12},
    {"id": 181304, "name": "Secret Hitler", "rating_average": 7.5, "min_players": 5, "max_players": 10},
    {"id": 244992, "name": "Just One", "rating_average": 7.6, "min_players": 3, "max_players": 7},
]

# 策略遊戲演示資料
DEMO_STRATEGY_GAMES = DEMO_GAMES[:5]

# 家庭遊戲演示資料
DEMO_FAMILY_GAMES = [
    {"id": 13, "name": "Catan", "rating_average": 7.2, "min_players": 3, "max_players": 4},
    {"id": 30549, "name": "Pandemic", "rating_average": 7.6, "min_players": 2, "max_players": 4},
    {"id": 36218, "name": "Dominion", "rating_average": 7.6, "min_players": 2, "max_players": 4},
    {"id": 68448, "name": "7 Wonders", "rating_average": 7.8, "min_players": 2, "max_players": 7},
    {"id": 148228, "name": "Splendor", "rating_average": 7.4, "min_players": 2, "max_players": 4},
]

# 兒童遊戲演示資料
DEMO_CHILDREN_GAMES = [
    {"id": 180621, "name": "Rhino Hero: Super Battle", "rating_average": 7.3, "min_players": 2, "max_players": 4},
    {"id": 8571, "name": "Animal Upon Animal", "rating_average": 7.0, "min_players": 2, "max_players": 4},
    {"id": 147020, "name": "Ice Cool", "rating_average": 6.9, "min_players": 2, "max_players": 4},
    {"id": 207051, "name": "Zombie Kidz Evolution", "rating_average": 7.6, "min_players": 2, "max_players": 4},
]

# 熱門遊戲演示資料
DEMO_HOT_GAMES = DEMO_GAMES[:10]
